### GET all contacts
GET https://contacts-api-jnau.onrender.com/contacts

### GET contact by ID
GET https://contacts-api-jnau.onrender.com/contacts/68685524fba07ccc17d3465a
### POST create new contact
POST https://contacts-api-jnau.onrender.com/contacts
Content-Type: application/json

{"_id":{"$oid":"68685524fba07ccc17d3465a"},
"firstName":"Norlando",
"lastName":"Junior",
"email":"norlandojr@hotmail.com",
"favoriteColor":"Blue",
"birthday":"2001-06-19"}

### PUT update contact
PUT https://contacts-api-jnau.onrender.com/contacts/68685524fba07ccc17d3465a
Content-Type: application/json

{"_id":{"$oid":"68685524fba07ccc17d3465a"},
"firstName":"Norlando",
"lastName":"Junior",
"email":"norlandojr@hotmail.com",
"favoriteColor":"Black",
"birthday":"2001-06-19"}

### DELETE contact
DELETE https://contacts-api-jnau.onrender.com/contacts/68704661038e53f4874c45b3
